# Версия docker-compose
version: '3.8'
# Список наших сервисов (контейнеров)

networks:
  default:
    external: true
    name: gateway
#  dev1:
#    internal: true

services:
  nginx:
    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.site01.nginx.rule=Host(`site01.localhost`)"
#      - "traefik.http.services.site01.nginx.loadbalancer.server.port=80"
#      - "traefik.docker.network=gateway"
      traefik.enable: "true"
      traefik.http.services.site01_nginx-80.loadbalancer.server.port: "80"
      traefik.http.routers.site01_nginx.entrypoints: "web"
      traefik.http.routers.site01_nginx.rule: "Host(`site01.localhost`)"
#      traefik.http.routers.site01_nginx.service: "site01.nginx-80"
    container_name: site01_nginx
    hostname: site01_nginx
    # используем последний стабильный образ nginx
    image: nginx:latest
    depends_on:
      - php
#    ports:
#      - '80:80'
    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/var/log/nginx
    # nginx должен общаться с php контейнером
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
    links:
      - php
    networks:
      - default
#      - dev1
  php:
    container_name: site01_php
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build: ./images/php
    # монтируем директорию с проектами
    volumes:
      - ./www:/var/www
      - ./images/php/:/usr/local/etc/php/custom.d
    depends_on:
      - postgresql
    networks:
      - default
  postgresql:
    image: 'bitnami/postgresql:latest'
    container_name: site01_postgres
    environment:
      - POSTGRESQL_USERNAME=site01
      - POSTGRESQL_PASSWORD=site01
      - POSTGRESQL_DATABASE=site01_db
    ports:
      - 5531:5432
    volumes:
      - /var/lib/postgresql/data
    networks:
      - default
#      - dev1